### PR TITLE
Cross build play-json for 2.11.12/2.7.4.

### LINKED ISSUE #45: Decouple scala/play-json versions
Should cross build play-json-25_2.11, play-json-27_2.11, play-json-27_2.13, etc.

### PR DESCRIPTION
**Pull request by htmldoug**
Resolves #45.

### CODE REVIEW

**Comment by htmldoug** [comment]
Mostly for @michaelleahy, you incrementalist.

**Comment by michaelleahy** [comment]
Potential tangent - with the release of 2.8, should we be bothering with 2.7?  We seem to have been lapped again...

**Comment by jducoeur** [comment]
Yeah, but tons of other libraries have moved to 2.7, and folks are poised to start implementing there.  So I think there's a lot of value in 2.7, although I don't know how many folks are planning on using the 2.11 / 2.7 combination for a substantial time.  (I expect recover-chat to pass through that on the way to 2.13 / 2.7, but hopefully as quickly as possible.)

It would be nice to nudge folks along toward 2.8, but I'd be pleasantly surprised if that gets really wide uptake this year...

**Comment by htmldoug** [comment]
I haven't been able to get mill to play nice with this. May need to punt. Can add later when someone actually needs it.

**Pull request closed without merging**
