### PR TITLE
Direct transformation between case classes and Mongo objects

### PR DESCRIPTION
**Pull request by russellremple**
(without intermediate Json string) 

@htmldoug: Need help integrating -- not clear on changes needed for Mill. Perhaps it would be better if this were a completely separate library from micropickle fork (so we don't have to introduce dependencies to lib-mongo, etc.) So just treat PR as for discussion/review only at this point until we have a chance to talk about it and decide.

### CODE REVIEW

**Comment by jducoeur** [comment]
Hmm.  Yeah, I would say that dependencies on lib-mongo are a no-no here.  That might warrant an Audax-side counterpart to the external weePickle repo; or, it might imply that this belongs in the lib-mongo repo itself.  (I'd probably argue for the latter, but I don't know lib-mongo at all well.)

Either way, this smells like a separate project to me, regardless of which repo it goes into.

**Comment by htmldoug** [comment]
A dependency on https://mvnrepository.com/artifact/org.mongodb/bson/3.11.1 would be fine. No different than depending on circe or play-json for those weePickle integrations.

Fine to incubate in another repo if you prefer.

**Comment by jducoeur** [comment]
I think a dependency on *public* Mongo code is reasonable, although I do think it's a bit more of a non-sequiteur than depending on the other JSON libraries, and starts getting into bloat IMO.  Depending on internal Rally libraries (which some of this code appears to do), not so much.

Still seems easier to me to put it into the lib-mongo repo: everything here looks appropriate to me as a project in there...

**Comment by htmldoug** [comment]
Questions on my mind for inclusion here are:
1. Can we nail down backwards binary compat here? I think probably, yes.
2. Would including it be potentially *useful* outside of Rally? I think also yes.
Consider why people used `PlayJsonMapper` despite the horrible perf. The killer feature is that it lets you reuse the same `Format` type classes. The capability to do that with weePickle for a tech as widely used as mongo, seems like it could be valuable outside of Rally.

Totally agree that it's easier to incubate internally, both for the bson integration and for weePickle. Better cohesion seems like the primary reason to include it here, but we can always decide to do that later, too.

**Comment by htmldoug** [comment]
Tests would be nice, particularly comparing against `BsonDocument.parse(String)` and `BsonDocument.toJson()`. How do they handle the non-json types?

**Comment by russellremple** [comment]
> A dependency on https://mvnrepository.com/artifact/org.mongodb/bson/3.11.1 would be fine. No different than depending on circe or play-json for those weePickle integrations.
> 
> Fine to incubate in another repo if you prefer.

I think I should. Of the four files, I think  *BsonValueTransformer.scala* and *NameValueTransformer.scala* probably belong here, and they would only add dependencies on org.bson._, no Rally libraries. I think WeeJsonMapperBson.scala (which depends on org.bson._ as well as Rally's spartan and lib-mongo) and WeeJsonMapper.scala (which also depends on these as well as casbah!) and their related tests really don't belong here. If it is okay with you guys, I think for now I am going to give "proton create <library_name>" a whirl and incubate there, so later we can decide what to put here, there, and everywhere. Unless there are objections, I'll call it lib-weepickle-extras. We could even put other Rally-only WeePickle-related stuff there that we don't think would be appropriate to contribute back to upickle.

**Comment by russellremple** [comment]
Incubating here: https://github.com/AudaxHealthInc/lib-weepickle-extras

**Pull request closed without merging**
